name: Update README

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate GitHub Stats
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          curl -H "Authorization: token $TOKEN" \
          https://github-readme-stats.vercel.app/api?username=DanD1511&show_icons=true&hide_border=true&count_private=true&include_all_commits=true > README.md
      - name: Commit and Push
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote set-url origin https://$TOKEN@github.com/DanD1511/DanD1511.git
          git add README.md
          git commit -m 'Update README with GitHub Stats'
          git push origin HEAD:main