name: Update README

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Generate GitHub Stats
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          curl -H "Authorization: token $GITHUB_TOKEN" \
          https://github-readme-stats.vercel.app/api?username=DanD1511&show_icons=true&hide_border=true&count_private=true&include_all_commits=true > README.md
      - name: Commit and Push
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const { execSync } = require('child_process');
            execSync('git config --global user.name "github-actions[bot]"');
            execSync('git config --global user.email "github-actions[bot]@users.noreply.github.com"');
            execSync('git add README.md');
            execSync('git commit -m "Update README with GitHub Stats"');
            execSync('git push');
